version: "3.9"

services:
  dynamic-quote-api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: dynamic-quote-api
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      -   dynamic-quote-api

networks:
  dynamic-quote-api: